### ISSUE TITLE
Editing doesnt seem to save

### ISSUE THREAD

**Issue by petesiss** [symfony-cmf/phpcrbrowser#10]
Is it expected that the editing doesnt seem to save? If I open a property and change it, then after clicking save it reverts to what it was before.

Sounds like a permission issue with my user, but after hours of googling and trying to understand how to properly manage jackrabbit users, which I'm still no closer to achieving due to most tools I've found being java classes or out of date, I thought I'd check it was actually supposed to be working before I spend any more time on it!

**Comment by dbu** [comment]
hi,

yes, that does not work. this tool is just a quick hack until we have something decent. @jakuza is working on a symfony bundle to replace the browser. once that is fine, we will probably provide some stand alone silex or symfony application instead of this code.

until that happens, you can write php scripts that create nodes.

sorry for this being in a not-so-ideal state at the moment.

**Comment by petesiss** [comment]
ok -  thanks for the response.
