### ISSUE TITLE
Can't create new node

### ISSUE THREAD

**Issue by hpatoio** [symfony-cmf/phpcrbrowser#9]
Hello, whenever I try to create a new node a get this message

 Error: document.getElementById("resp") is null
 Source File: http://phpcrbrowser.lan/static/js/crbrowser.js
 Line: 512

Regards

**Comment by dbu** [comment]
hi,

yes, afaik that does not work. this tool is just a quick hack until we have something decent. @jakuza is working on a symfony bundle to replace the browser. once that is fine, we will probably provide some stand alone silex or symfony application instead of this code.

until that happens, you can write php scripts that create nodes.

sorry for this being in a not-so-ideal state at the moment.
